The Act of Web Scrapping Using Python Libraries

In [ ]:
import numpy as np
import pandas as pd
import requests

In [ ]:
#uncomment below to install plotly
!pip install plotly

import plotly.express as px

Requirement already satisfied: plotly in /usr/local/lib/python3.10/dist-packages (5.15.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly) (8.2.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from plotly) (23.2)

In [ ]:
url = "https://en.wikipedia.org/wiki/List_of_highest-grossing_films"

# Fetch all the tables from the web page
tables_list = pd.read_html(url)
tables_list

[    Rank  Peak                                          Title  \
 0      1     1                                         Avatar
 1      2     1                              Avengers: Endgame
 2      3     3                       Avatar: The Way of Water
 3      4     1                                        Titanic
 4      5     3                   Star Wars: The Force Awakens
 5      6     4                         Avengers: Infinity War
 6      7     6                        Spider-Man: No Way Home
 7      8     3                                 Jurassic World
 8      9     7                                  The Lion King
 9     10     3                                   The Avengers
 10    11     4                                      Furious 7
 11    12    11                              Top Gun: Maverick
 12    13    10                                      Frozen II
 13    14    14                                       Barbie †
 14    15     5                        Avengers: Age of Ultron
 15    16    15                  The Super Mario Bros. Movie †
 16    17     9                                  Black Panther
 17    18     3  Harry Potter and the Deathly Hallows – Part 2
 18    19     9                       Star Wars: The Last Jedi
 19    20    12                 Jurassic World: Fallen Kingdom
 20    21     5                                         Frozen
 21    22    10                           Beauty and the Beast
 22    23    15                                  Incredibles 2
 23    24    11                        The Fate of the Furious
 24    25     5                                     Iron Man 3
 25    26    10                                        Minions
 26    27    12                     Captain America: Civil War
 27    28    20                                        Aquaman
 28    29     2  The Lord of the Rings: The Return of the King
 29    30  24RK                      Spider-Man: Far From Home
 30    31  23RK                                 Captain Marvel
 31    32   5RK                 Transformers: Dark of the Moon
 32    33     7                                        Skyfall
 33    34    10                Transformers: Age of Extinction
 34    35     7                          The Dark Knight Rises
 35    36    31                                          Joker
 36    37    32               Star Wars: The Rise of Skywalker
 37    38    30                                    Toy Story 4
 38    39  4TS3                                    Toy Story 3
 39    40     3     Pirates of the Caribbean: Dead Man's Chest
 40    41    20                   Rogue One: A Star Wars Story
 41    42    34                                        Aladdin
 42    43     6    Pirates of the Caribbean: On Stranger Tides
 43    44     1                                  Jurassic Park
 44    45    24                                Despicable Me 3
 45    46    22                                   Finding Dory
 46    47     2      Star Wars: Episode I – The Phantom Menace
 47    48     5                            Alice in Wonderland
 48    49    24                                       Zootopia
 49    50    14              The Hobbit: An Unexpected Journey

      Worldwide gross  Year  Reference(s)
 0     $2,923,706,026  2009    [# 1][# 2]
 1     $2,797,501,328  2019    [# 3][# 4]
 2     $2,320,250,281  2022    [# 5][# 6]
 3    T$2,257,844,554  1997    [# 7][# 8]
 4     $2,068,223,624  2015   [# 9][# 10]
 5     $2,048,359,754  2018  [# 11][# 12]
 6     $1,921,847,111  2021  [# 13][# 14]
 7     $1,671,537,444  2015  [# 15][# 16]
 8     $1,656,943,394  2019   [# 17][# 4]
 9     $1,518,815,515  2012  [# 18][# 19]
 10    $1,515,341,399  2015  [# 20][# 21]
 11    $1,495,696,292  2022  [# 22][# 23]
 12    $1,450,026,933  2019  [# 24][# 25]
 13    $1,441,613,396  2023  [# 26][# 27]
 14    $1,402,809,540  2015  [# 28][# 21]
 15    $1,361,927,918  2023  [# 29][# 30]
 16    $1,347,280,838  2018  [# 31][# 32]
 17    $1,342,139,727  2011  [# 33][# 34]
 18    $1,332,539,889  2017  [# 35][# 36]
 19    $1,308,473,425  2018  [# 37][# 12]
 20   F$1,290,000,000  2013  [# 38][# 39]
 21    $1,263,521,126  2017  [# 40][# 41]
 22    $1,242,805,359  2018  [# 42][# 12]
 23  F8$1,238,764,765  2017  [# 43][# 41]
 24    $1,214,811,252  2013  [# 44][# 45]
 25    $1,159,444,662  2015  [# 46][# 16]
 26    $1,153,337,496  2016  [# 47][# 48]
 27    $1,148,528,393  2018  [# 49][# 12]
 28    $1,147,997,407  2003  [# 50][# 51]
 29    $1,131,927,996  2019   [# 52][# 4]
 30    $1,128,274,794  2019  [# 53][# 54]
 31    $1,123,794,079  2011  [# 55][# 34]
 32    $1,108,569,499  2012  [# 56][# 57]
 33    $1,104,054,072  2014  [# 58][# 59]
 34    $1,081,169,825  2012  [# 60][# 61]
 35    $1,074,458,282  2019  [# 62][# 25]
 36    $1,074,144,248  2019  [# 63][# 25]
 37    $1,073,394,593  2019   [# 64][# 4]
 38    $1,066,970,811  2010  [# 65][# 66]
 39    $1,066,179,747  2006  [# 67][# 68]
 40    $1,057,420,387  2016  [# 69][# 70]
 41    $1,050,693,953  2019   [# 71][# 4]
 42    $1,045,713,802  2011  [# 72][# 66]
 43    $1,037,535,230  1993  [# 73][# 74]
 44    $1,034,800,131  2017  [# 75][# 41]
 45    $1,028,570,942  2016  [# 76][# 77]
 46    $1,027,082,707  1999   [# 78][# 8]
 47    $1,025,468,216  2010  [# 79][# 80]
 48    $1,023,784,195  2016  [# 81][# 48]
 49    $1,017,030,651  2012  [# 82][# 83]  ,
    Rank                         Title Worldwide gross (2022 $)  Year
 0     1            Gone with the Wind           $4,192,000,000  1939
 1     2                        Avatar         A1$3,824,000,000  2009
 2     3                       Titanic          T$3,485,000,000  1997
 3     4                     Star Wars           $3,443,000,000  1977
 4     5             Avengers: Endgame         AE$3,165,000,000  2019
 5     6            The Sound of Music           $2,884,000,000  1965
 6     7    E.T. the Extra-Terrestrial           $2,815,000,000  1982
 7     8          The Ten Commandments           $2,665,000,000  1956
 8     9                Doctor Zhivago           $2,526,000,000  1965
 9    10  Star Wars: The Force Awakens        TFA$2,491,000,000  2015,
      Year                      Title  \
 0    1915      The Birth of a Nation
 1    1916                Intolerance
 2    1917                  Cleopatra
 3    1918                     Mickey
 4    1919            The Miracle Man
 ..    ...                        ...
 144  2019          Avengers: Endgame
 145  2020  Demon Slayer: Mugen Train
 146  2021    Spider-Man: No Way Home
 147  2022   Avatar: The Way of Water
 148  2023                   Barbie †

                                        Worldwide gross  \
 0    $50,000,000–100,000,000 $20,000,000+R ($5,200,...
 1                                       $1,750,000R IN
 2                                           $500,000*R
 3                                           $8,000,000
 4                                          $3,000,000R
 ..                                                 ...
 144                                     $2,797,501,328
 145                                       $507,127,293
 146                    $1,921,847,111 ($1,912,233,593)
 147                                     $2,320,250,281
 148                                     $1,441,613,396

                        Budget         Reference(s)
 0                    $110,000   [# 84][# 85][# 86]
 1                    $385,907             [50][51]
 2                    $300,000         [# 87][# 88]
 3                    $250,000               [# 89]
 4                    $120,000               [# 90]
 ..                        ...                  ...
 144              $356,000,000                [# 3]
 145               $15,750,000              [# 305]
 146              $200,000,000        [# 13][# 306]
 147  $350,000,000–460,000,000  [# 5][# 307][# 308]
 148  $128,000,000–145,000,000         [# 26][# 27]

 [149 rows x 5 columns],
      Established                       Title        Record-setting gross  \
 0       1915[64]       The Birth of a Nation                 $5,200,000R
 1           1940       The Birth of a Nation              $15,000,000R ‡
 2       1940[32]          Gone with the Wind                $32,000,000R
 3           1963          Gone with the Wind              $67,000,000R ‡
 4       1966[64]          The Sound of Music               $114,600,000R
 5       1971[64]          Gone with the Wind             $116,000,000R ‡
 6       1972[64]               The Godfather   $127,600,000–142,000,000R
 7   1976[87][88]                        Jaws               $193,700,000R
 8   1978[89][90]                   Star Wars  $410,000,000/$268,500,000R
 9           1982                   Star Wars              $530,000,000 ‡
 10      1983[91]  E.T. the Extra-Terrestrial    $619,000,000–664,000,000
 11          1993  E.T. the Extra-Terrestrial              $701,000,000 ‡
 12      1993[64]               Jurassic Park                $912,667,947
 13      1998[92]                     Titanic              $1,843,373,318
 14  2010[93][94]                      Avatar              $2,743,577,587
 15  2010[93][94]                      Avatar            $2,788,416,135 ‡
 16  2019[95][96]           Avengers: Endgame              $2,797,501,328
 17      2021[97]                      Avatar            $2,847,397,339 ‡
 18          2022                      Avatar            $2,923,706,026 ‡

       Reference(s)
 0           [# 85]
 1          [# 309]
 2          [# 135]
 3          [# 310]
 4          [# 210]
 5          [# 311]
 6   [# 236][# 312]
 7          [# 251]
 8   [# 313][# 236]
 9          [# 257]
 10  [# 257][# 270]
 11         [# 314]
 12          [# 73]
 13           [# 7]
 14           [# 1]
 15           [# 1]
 16           [# 3]
 17           [# 1]
 18           [# 1]  ,
                                                      0  \
 0    Rank Series Total worldwide gross No. of films...
 1                                                 Rank
 2    1 Marvel Cinematic UniverseS $29,621,205,938 3...
 3                                                    1
 4    The Infinity Saga $22,587,759,303 23 $982,076,...
 ..                                                 ...
 356                                                  3
 357                                                  4
 358                                                  5
 359                      Lightyear (2022) $226,425,420
 360                                                NaN

                                                      1  \
 0    Rank Series Total worldwide gross No. of films...
 1                                               Series
 2    1 Marvel Cinematic UniverseS $29,621,205,938 3...
 3                           Marvel Cinematic UniverseS
 4    The Infinity Saga $22,587,759,303 23 $982,076,...
 ..                                                 ...
 356                                 Toy Story 2 (1999)
 357                                   Toy Story (1995)
 358                  Toy Story/Toy Story 2 (3D) (2009)
 359                      Lightyear (2022) $226,425,420
 360                                   Lightyear (2022)

                                                      2  \
 0    Rank Series Total worldwide gross No. of films...
 1                                Total worldwide gross
 2    1 Marvel Cinematic UniverseS $29,621,205,938 3...
 3                                      $29,621,205,938
 4    The Infinity Saga $22,587,759,303 23 $982,076,...
 ..                                                 ...
 356                                       $497,375,381
 357                                       $373,554,033
 358                                        $32,284,600
 359                      Lightyear (2022) $226,425,420
 360                                       $226,425,420

                                                      3  \
 0    Rank Series Total worldwide gross No. of films...
 1                                         No. of films
 2    1 Marvel Cinematic UniverseS $29,621,205,938 3...
 3                                                   32
 4    The Infinity Saga $22,587,759,303 23 $982,076,...
 ..                                                 ...
 356                                                NaN
 357                                                NaN
 358                                                NaN
 359                      Lightyear (2022) $226,425,420
 360                                                NaN

                                                      4  \
 0    Rank Series Total worldwide gross No. of films...
 1                                     Average of films
 2    1 Marvel Cinematic UniverseS $29,621,205,938 3...
 3                                         $925,662,686
 4    The Infinity Saga $22,587,759,303 23 $982,076,...
 ..                                                 ...
 356                                                NaN
 357                                                NaN
 358                                                NaN
 359                      Lightyear (2022) $226,425,420
 360                                                NaN

                                                      5
 0    Rank Series Total worldwide gross No. of films...
 1                                Highest-grossing film
 2    1 Marvel Cinematic UniverseS $29,621,205,938 3...
 3                   Avengers: Endgame ($2,797,501,328)
 4    The Infinity Saga $22,587,759,303 23 $982,076,...
 ..                                                 ...
 356                                                NaN
 357                                                NaN
 358                                                NaN
 359                      Lightyear (2022) $226,425,420
 360                                                NaN

 [361 rows x 6 columns],
 Empty DataFrame
 Columns: [Rank, Series, Total worldwide gross, No. of films, Average of films, Highest-grossing film]
 Index: [],
                                                     0  \
 0                                                   1
 1   The Infinity Saga $22,587,759,303 23 $982,076,...
 2                                                 NaN
 3   Phase Three $13,505,059,275 11 $1,227,732,661 ...
 4                                                 NaN
 5                                                   1
 6                                                   2
 7                                                   3
 8                                                   4
 9                                                   5
 10                                                  6
 11                                                  7
 12                                                  8
 13                                                  9
 14                                                 10
 15                                                 11
 16  Phase Two $5,269,487,547 6 $878,247,925 Avenge...
 17                                                NaN
 18                                                  1
 19                                                  2
 20                                                  3
 21                                                  4
 22                                                  5
 23                                                  6
 24  Phase One $3,813,212,481 6 $635,535,414 The Av...
 25                                                NaN
 26                                                  1
 27                                                  2
 28                                                  3
 29                                                  4
 30                                                  5
 31                                                  6
 32  The Multiverse Saga $7,033,446,635 9 $781,494,...
 33                                                NaN
 34  Phase Four $5,711,819,678 7 $815,974,240 Spide...
 35                                                NaN
 36                                                  1
 37                                                  2
 38                                                  3
 39                                                  4
 40                                                  5
 41                                                  6
 42                                                  7
 43  Phase Five $1,321,626,957 2 $660,813,479 Guard...
 44                                                NaN
 45                                                  1
 46                                                  2

                                                     1  \
 0                          Marvel Cinematic UniverseS
 1   The Infinity Saga $22,587,759,303 23 $982,076,...
 2                                   The Infinity Saga
 3   Phase Three $13,505,059,275 11 $1,227,732,661 ...
 4                                         Phase Three
 5                            Avengers: Endgame (2019)
 6                       Avengers: Infinity War (2018)
 7                                Black Panther (2018)
 8                   Captain America: Civil War (2016)
 9                    Spider-Man: Far From Home (2019)
 10                              Captain Marvel (2019)
 11                      Spider-Man: Homecoming (2017)
 12              Guardians of the Galaxy Vol. 2 (2017)
 13                              Thor: Ragnarok (2017)
 14                              Doctor Strange (2016)
 15                        Ant-Man and the Wasp (2018)
 16  Phase Two $5,269,487,547 6 $878,247,925 Avenge...
 17                                          Phase Two
 18                     Avengers: Age of Ultron (2015)
 19                                  Iron Man 3 (2013)
 20                     Guardians of the Galaxy (2014)
 21         Captain America: The Winter Soldier (2014)
 22                        Thor: The Dark World (2013)
 23                                     Ant-Man (2015)
 24  Phase One $3,813,212,481 6 $635,535,414 The Av...
 25                                          Phase One
 26                                The Avengers (2012)
 27                                  Iron Man 2 (2010)
 28                                    Iron Man (2008)
 29                                        Thor (2011)
 30          Captain America: The First Avenger (2011)
 31                         The Incredible Hulk (2008)
 32  The Multiverse Saga $7,033,446,635 9 $781,494,...
 33                                The Multiverse Saga
 34  Phase Four $5,711,819,678 7 $815,974,240 Spide...
 35                                         Phase Four
 36                     Spider-Man: No Way Home (2021)
 37  Doctor Strange in the Multiverse of Madness (2...
 38              Black Panther: Wakanda Forever (2022)
 39                      Thor: Love and Thunder (2022)
 40   Shang-Chi and the Legend of the Ten Rings (2021)
 41                                    Eternals (2021)
 42                                 Black Widow (2021)
 43  Phase Five $1,321,626,957 2 $660,813,479 Guard...
 44                                         Phase Five
 45              Guardians of the Galaxy Vol. 3 (2023)
 46           Ant-Man and the Wasp: Quantumania (2023)

                                                     2  \
 0                                     $29,621,205,938
 1   The Infinity Saga $22,587,759,303 23 $982,076,...
 2                                     $22,587,759,303
 3   Phase Three $13,505,059,275 11 $1,227,732,661 ...
 4                                     $13,505,059,275
 5                                      $2,797,501,328
 6                                      $2,048,359,754
 7                                      $1,347,280,838
 8                                      $1,153,337,496
 9                                      $1,131,927,996
 10                                     $1,128,274,794

In [ ]:
# How many tables were returned?
len(tables_list)

89

In [ ]:
# We're only interested in the first table
df = tables_list[0]
df.head()

   Rank Peak                         Title  Worldwide gross  Year Reference(s)
0     1    1                        Avatar   $2,923,706,026  2009   [# 1][# 2]
1     2    1             Avengers: Endgame   $2,797,501,328  2019   [# 3][# 4]
2     3    3      Avatar: The Way of Water   $2,320,250,281  2022   [# 5][# 6]
3     4    1                       Titanic  T$2,257,844,554  1997   [# 7][# 8]
4     5    3  Star Wars: The Force Awakens   $2,068,223,624  2015  [# 9][# 10]

In [ ]:
# Let's remove the "Reference" column since we don't need it
df = df.drop(columns=["Reference(s)"])
df

,Rank,Peak,Title,Worldwide gross,Year
0,1,1,Avatar,"$2,923,706,026",2009
1,2,1,Avengers: Endgame,"$2,797,501,328",2019
2,3,3,Avatar: The Way of Water,"$2,320,250,281",2022
3,4,1,Titanic,"T$2,257,844,554",1997
4,5,3,Star Wars: The Force Awakens,"$2,068,223,624",2015
5,6,4,Avengers: Infinity War,"$2,048,359,754",2018
6,7,6,Spider-Man: No Way Home,"$1,921,847,111",2021
7,8,3,Jurassic World,"$1,671,537,444",2015
8,9,7,The Lion King,"$1,656,943,394",2019
9,10,3,The Avengers,"$1,518,815,515",2012
10,11,4,Furious 7,"$1,515,341,399",2015
11,12,11,Top Gun: Maverick,"$1,495,696,292",2022
12,13,10,Frozen II,"$1,450,026,933",2019
13,14,14,Barbie †,"$1,441,613,396",2023
14,15,5,Avengers: Age of Ultron,"$1,402,809,540",2015
15,16,15,The Super Mario Bros. Movie †,"$1,361,927,918",2023
16,17,9,Black Panther,"$1,347,280,838",2018
17,18,3,Harry Potter and the Deathly Hallows – Part 2,"$1,342,139,727",2011
18,19,9,Star Wars: The Last Jedi,"$1,332,539,889",2017
19,20,12,Jurassic World: Fallen Kingdom,"$1,308,473,425",2018
20,21,5,Frozen,"F$1,290,000,000",2013
21,22,10,Beauty and the Beast,"$1,263,521,126",2017
22,23,15,Incredibles 2,"$1,242,805,359",2018
23,24,11,The Fate of the Furious,"F8$1,238,764,765",2017
24,25,5,Iron Man 3,"$1,214,811,252",2013
25,26,10,Minions,"$1,159,444,662",2015
26,27,12,Captain America: Civil War,"$1,153,337,496",2016
27,28,20,Aquaman,"$1,148,528,393",2018
28,29,2,The Lord of the Rings: The Return of the King,"$1,147,997,407",2003
29,30,24RK,Spider-Man: Far From Home,"$1,131,927,996",2019
30,31,23RK,Captain Marvel,"$1,128,274,794",2019
31,32,5RK,Transformers: Dark of the Moon,"$1,123,794,079",2011
32,33,7,Skyfall,"$1,108,569,499",2012
33,34,10,Transformers: Age of Extinction,"$1,104,054,072",2014
34,35,7,The Dark Knight Rises,"$1,081,169,825",2012
35,36,31,Joker,"$1,074,458,282",2019
36,37,32,Star Wars: The Rise of Skywalker,"$1,074,144,248",2019
37,38,30,Toy Story 4,"$1,073,394,593",2019
38,39,4TS3,Toy Story 3,"$1,066,970,811",2010
39,40,3,Pirates of the Caribbean: Dead Man's Chest,"$1,066,179,747",2006
40,41,20,Rogue One: A Star Wars Story,"$1,057,420,387",2016
41,42,34,Aladdin,"$1,050,693,953",2019
42,43,6,Pirates of the Caribbean: On Stranger Tides,"$1,045,713,802",2011
43,44,1,Jurassic Park,"$1,037,535,230",1993
44,45,24,Despicable Me 3,"$1,034,800,131",2017
45,46,22,Finding Dory,"$1,028,570,942",2016
46,47,2,Star Wars: Episode I – The Phantom Menace,"$1,027,082,707",1999
47,48,5,Alice in Wonderland,"$1,025,468,216",2010
48,49,24,Zootopia,"$1,023,784,195",2016
49,50,14,The Hobbit: An Unexpected Journey,"$1,017,030,651",2012

In [ ]:
# Let's perform data cleaning
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Rank             50 non-null     int64
 1   Peak             50 non-null     object
 2   Title            50 non-null     object
 3   Worldwide gross  50 non-null     object
 4   Year             50 non-null     int64
dtypes: int64(2), object(3)
memory usage: 2.1+ KB

In [ ]:
# Remove the RK string from some rows in the Peak column

df['Peak'] = df['Peak'].astype('str').str.extractall('(\d+)').unstack().fillna('').sum(axis=1).astype(int)

# Remove "$" and "," string from the rows in the Worgross'ldwide gross column
df['Worldwide gross'] = df['Worldwide gross'].astype('str').str.extractall('(\d+)').unstack().fillna('').sum(axis=1).astype(int)

In [ ]:
# change data types for some columns
df = df.astype(
    {'Peak': 'int64',
     'Year': 'category',
     }
)

df

,Rank,Peak,Title,Worldwide gross,Year
0,1,1,Avatar,2923706026,2009
1,2,1,Avengers: Endgame,2797501328,2019
2,3,3,Avatar: The Way of Water,2320250281,2022
3,4,1,Titanic,2257844554,1997
4,5,3,Star Wars: The Force Awakens,2068223624,2015
5,6,4,Avengers: Infinity War,2048359754,2018
6,7,6,Spider-Man: No Way Home,1921847111,2021
7,8,3,Jurassic World,1671537444,2015
8,9,7,The Lion King,1656943394,2019
9,10,3,The Avengers,1518815515,2012
10,11,4,Furious 7,1515341399,2015
11,12,11,Top Gun: Maverick,1495696292,2022
12,13,10,Frozen II,1450026933,2019
13,14,14,Barbie †,1441613396,2023
14,15,5,Avengers: Age of Ultron,1402809540,2015
15,16,15,The Super Mario Bros. Movie †,1361927918,2023
16,17,9,Black Panther,1347280838,2018
17,18,3,Harry Potter and the Deathly Hallows – Part 2,1342139727,2011
18,19,9,Star Wars: The Last Jedi,1332539889,2017
19,20,12,Jurassic World: Fallen Kingdom,1308473425,2018
20,21,5,Frozen,1290000000,2013
21,22,10,Beauty and the Beast,1263521126,2017
22,23,15,Incredibles 2,1242805359,2018
23,24,11,The Fate of the Furious,81238764765,2017
24,25,5,Iron Man 3,1214811252,2013
25,26,10,Minions,1159444662,2015
26,27,12,Captain America: Civil War,1153337496,2016
27,28,20,Aquaman,1148528393,2018
28,29,2,The Lord of the Rings: The Return of the King,1147997407,2003
29,30,24,Spider-Man: Far From Home,1131927996,2019
30,31,23,Captain Marvel,1128274794,2019
31,32,5,Transformers: Dark of the Moon,1123794079,2011
32,33,7,Skyfall,1108569499,2012
33,34,10,Transformers: Age of Extinction,1104054072,2014
34,35,7,The Dark Knight Rises,1081169825,2012
35,36,31,Joker,1074458282,2019
36,37,32,Star Wars: The Rise of Skywalker,1074144248,2019
37,38,30,Toy Story 4,1073394593,2019
38,39,43,Toy Story 3,1066970811,2010
39,40,3,Pirates of the Caribbean: Dead Man's Chest,1066179747,2006
40,41,20,Rogue One: A Star Wars Story,1057420387,2016
41,42,34,Aladdin,1050693953,2019
42,43,6,Pirates of the Caribbean: On Stranger Tides,1045713802,2011
43,44,1,Jurassic Park,1037535230,1993
44,45,24,Despicable Me 3,1034800131,2017
45,46,22,Finding Dory,1028570942,2016
46,47,2,Star Wars: Episode I – The Phantom Menace,1027082707,1999
47,48,5,Alice in Wonderland,1025468216,2010
48,49,24,Zootopia,1023784195,2016
49,50,14,The Hobbit: An Unexpected Journey,1017030651,2012

In [ ]:
# Now, let's get additional data about each movie

genre = [
        "Science Fiction", "Superhero", "Science Fiction", "Romance",
        "Science Fiction", "Superhero", "Superhero",
        "Action", "Musical Drama", "Superhero", "Action",
        "Action", "Animation", "Animation", "Superhero",
        "Animation", "Superhero", "Thriller", "Science Fiction",
        "Action", "Animation", "Animation", "Animation", "Action",
        "Superhero", "Animation", "Superhero", "Superhero",
        "Adventure", "Superhero", "Superhero", "Science Fiction",
        "Action", "Science Fiction", "Superhero", "Thriller",
        "Science Fiction", "Animation", "Animation",
        "Adventure", "Science Fiction", "Action", "Animation",
        "Animation", "Action", "Action", "Science Fiction",
        "Fantasy", "Animation", "Adventure"
]

In [ ]:

df["Genre"] = genre
df

,Rank,Peak,Title,Worldwide gross,Year,Genre
0,1,1,Avatar,2923706026,2009,Science Fiction
1,2,1,Avengers: Endgame,2797501328,2019,Superhero
2,3,3,Avatar: The Way of Water,2320250281,2022,Science Fiction
3,4,1,Titanic,2257844554,1997,Romance
4,5,3,Star Wars: The Force Awakens,2068223624,2015,Science Fiction
5,6,4,Avengers: Infinity War,2048359754,2018,Superhero
6,7,6,Spider-Man: No Way Home,1921847111,2021,Superhero
7,8,3,Jurassic World,1671537444,2015,Action
8,9,7,The Lion King,1656943394,2019,Musical Drama
9,10,3,The Avengers,1518815515,2012,Superhero
10,11,4,Furious 7,1515341399,2015,Action
11,12,11,Top Gun: Maverick,1495696292,2022,Action
12,13,10,Frozen II,1450026933,2019,Animation
13,14,14,Barbie †,1441613396,2023,Animation
14,15,5,Avengers: Age of Ultron,1402809540,2015,Superhero
15,16,15,The Super Mario Bros. Movie †,1361927918,2023,Animation
16,17,9,Black Panther,1347280838,2018,Superhero
17,18,3,Harry Potter and the Deathly Hallows – Part 2,1342139727,2011,Thriller
18,19,9,Star Wars: The Last Jedi,1332539889,2017,Science Fiction
19,20,12,Jurassic World: Fallen Kingdom,1308473425,2018,Action
20,21,5,Frozen,1290000000,2013,Animation
21,22,10,Beauty and the Beast,1263521126,2017,Animation
22,23,15,Incredibles 2,1242805359,2018,Animation
23,24,11,The Fate of the Furious,81238764765,2017,Action
24,25,5,Iron Man 3,1214811252,2013,Superhero
25,26,10,Minions,1159444662,2015,Animation
26,27,12,Captain America: Civil War,1153337496,2016,Superhero
27,28,20,Aquaman,1148528393,2018,Superhero
28,29,2,The Lord of the Rings: The Return of the King,1147997407,2003,Adventure
29,30,24,Spider-Man: Far From Home,1131927996,2019,Superhero
30,31,23,Captain Marvel,1128274794,2019,Superhero
31,32,5,Transformers: Dark of the Moon,1123794079,2011,Science Fiction
32,33,7,Skyfall,1108569499,2012,Action
33,34,10,Transformers: Age of Extinction,1104054072,2014,Science Fiction
34,35,7,The Dark Knight Rises,1081169825,2012,Superhero
35,36,31,Joker,1074458282,2019,Thriller
36,37,32,Star Wars: The Rise of Skywalker,1074144248,2019,Science Fiction
37,38,30,Toy Story 4,1073394593,2019,Animation
38,39,43,Toy Story 3,1066970811,2010,Animation
39,40,3,Pirates of the Caribbean: Dead Man's Chest,1066179747,2006,Adventure
40,41,20,Rogue One: A Star Wars Story,1057420387,2016,Science Fiction
41,42,34,Aladdin,1050693953,2019,Action
42,43,6,Pirates of the Caribbean: On Stranger Tides,1045713802,2011,Animation
43,44,1,Jurassic Park,1037535230,1993,Animation
44,45,24,Despicable Me 3,1034800131,2017,Action
45,46,22,Finding Dory,1028570942,2016,Action
46,47,2,Star Wars: Episode I – The Phantom Menace,1027082707,1999,Science Fiction
47,48,5,Alice in Wonderland,1025468216,2010,Fantasy
48,49,24,Zootopia,1023784195,2016,Animation
49,50,14,The Hobbit: An Unexpected Journey,1017030651,2012,Adventure

## Now, the data has been cleaned. Let's perform some analyses

In [ ]:
df.describe()

           Rank       Peak  Worldwide gross
count  50.00000  50.000000     5.000000e+01
mean   25.50000  11.620000     2.968463e+09
std    14.57738  10.157715     1.130390e+10
min     1.00000   1.000000     1.017031e+09
25%    13.25000   4.000000     1.073582e+09
50%    25.50000   9.000000     1.187128e+09
75%    37.75000  15.000000     1.484279e+09
max    50.00000  43.000000     8.123876e+10

from matplotlib import pyplot as plt
_df_0['Rank'].plot(kind='hist', bins=20, title='Rank')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['Peak'].plot(kind='hist', bins=20, title='Peak')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['Worldwide gross'].plot(kind='hist', bins=20, title='Worldwide gross')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3.plot(kind='scatter', x='Rank', y='Peak', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='Peak', y='Worldwide gross', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5['Rank'].plot(kind='line', figsize=(8, 4), title='Rank')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_6['Peak'].plot(kind='line', figsize=(8, 4), title='Peak')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_7['Worldwide gross'].plot(kind='line', figsize=(8, 4), title='Worldwide gross')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
#Which movie grossed the highest revenue?
#df["Worldwide gross"].max()

df.nlargest(1, "Worldwide gross")

    Rank  Peak                    Title  Worldwide gross  Year   Genre
23    24    11  The Fate of the Furious      81238764765  2017  Action

Observation: The 'The Fate of the Furious' movie garnered the highest gross revenue

In [ ]:
#Worldwide gross by genre
px.bar(data_frame=df, x="Genre", y="Worldwide gross")